modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "GNU GENERAL PUBLIC LICENSE Version 3"
issueTrackerURL = "https://github.com/alRex-U/ParCool/issues" #optional
[[mods]] #mandatory
modId = "parcool" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "ParCool!" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/parcool" #optional
logoFile = "parcool_logo.png" #optional
# credits = "" #optional
authors = 'alRex_U'
description = '''
    This enable us act like parkour players.
    Enjoy Minecraft with cool actions!
    If Patchouli mod is installed, let's read ParCool Guide!
'''
[[dependencies.parcool]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.parcool]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
