modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/alRex-U/ParCool/issues" #optional
[[mods]] #mandatory
modId = "parcool" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "ParCool!" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/parcool" #optional
logoFile = "../parcool_logo.png" #optional
# credits = "" #optional
authors = 'alRex_U'
description = '''
    This enable us act like parkour players.
    Enjoy Minecraft with cool actions!
    If Patchouli mod is installed, let's read ParCool Guide!
'''

[[mixins]]
config = "parcool.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.parcool]] #optional
modId = "neoforge" #mandatory
type = "required"
versionRange = "${neo_forge_version}" #mandatory
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering = "NONE"
side = "BOTH"

[[dependencies.parcool]]
modId = "minecraft"
type = "required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.parcool]]
modId = "shouldersurfing"
type = "optional"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.21.1-4.11.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.parcool]]
modId = "betterthirdperson"
type = "optional"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.9.0,)"
ordering = "NONE"
side = "BOTH"
